-- Spec 2.9: the plan, and Spec 2.10: the refs.
--
-- A run row says what a run did and a staged experiment says what was
-- registered. The plan is the row for what an operator is still composing,
-- so that a column trimmed before registration is still a fact about what
-- was considered rather than nothing at all.

-- Spec 2.9: one parent run, which every column branches from, and the
-- author and version every authored row carries per section 3.2. The author
-- has no default: a null is passed rather than fallen into, so an author
-- nobody could name stays distinguishable from one nobody asked for.
-- Spec 2: an authored row's identity says what it addresses.
--
-- **The generator and the shape are stated once each and not per table.**
-- Three tables repeating both expressions is three chances for a paste that
-- updates one and not the other, which yields a table where every plain
-- insert fails a check nobody reads until something writes to it.
--
-- **Sixteen hex of uniform randomness, and not sixteen taken off a v4
-- UUID.** A v4's thirteenth hex is the version nibble and is always `4`, so
-- the first sixteen carry sixty bits rather than sixty-four - and a check
-- written for sixteen free nibbles then admits spellings the generator can
-- never produce, which is the gap between what the schema holds and what the
-- store writes. The two slices below skip the version and the variant.
CREATE FUNCTION weaver_key(prefix TEXT) RETURNS TEXT AS $$
  SELECT prefix || '-' || substr(h, 1, 12) || substr(h, 18, 4)
  FROM (SELECT replace(gen_random_uuid()::text, '-', '') AS h) t;
$$ LANGUAGE sql VOLATILE;

-- **A domain per kind, so the prefix is written once.** The check travels
-- with the type rather than with each table that uses it, and a fourth kind
-- is a domain rather than a fourth copy of a regular expression.
--
-- **What this holds and what it does not.** It holds that a key is spelled
-- for its kind, so an arm's identity offered where a plan's is owed is
-- refused at the boundary. It does not hold that the store generated it: a
-- TEXT key with a default is one a writer may supply, where the sequence
-- this replaced could only be overridden explicitly. That is a real loss
-- and it is stated rather than papered over - the kind in the value is what
-- the change buys, and provenance is not.
CREATE DOMAIN plan_id AS TEXT CHECK (VALUE ~ '^pl-[0-9a-f]{16}$');
CREATE DOMAIN arm_id AS TEXT CHECK (VALUE ~ '^ar-[0-9a-f]{16}$');
CREATE DOMAIN ref_id AS TEXT CHECK (VALUE ~ '^rf-[0-9a-f]{16}$');

-- **The identity says what the row is and says this crate authored it.**
-- Two letters and sixteen hex, generated by the store. A bare integer is a
-- valid value for every other table's key, so nothing catches a plan's
-- identity handed where an experiment's was meant - not the compiler, not
-- this schema, and not a link. The prefix is checked rather than assumed,
-- since an identity the store generates is one the store can hold to shape.
--
-- **A run does not take this**, and that is the convention rather than an
-- exception to it: section 2.2 has a run's identity as the record spells it,
-- so a prefixed spelling would be an identity written over one received.
-- **The shape of a key says whether the row was authored here or landed
-- here.**
--
-- **The artifact is authored and does take it**, and does not carry it yet.
-- Its record identity is a digest the SPU computed, which is a member rather
-- than a key - a row's half and a member's provenance being different
-- questions. Sections 2.3, 2.4 and 2.5 keep their sequences until the act
-- that converts them, which section 2 declares rather than leaving to be
-- found.
CREATE TABLE plan (
  plan_id        plan_id PRIMARY KEY DEFAULT weaver_key('pl'),
  parent_run_id  TEXT NOT NULL REFERENCES run(run_id),
  author         TEXT,
  version        BIGINT NOT NULL DEFAULT 1,

  -- **The plan's only monotonic member.** The sequence this key replaced
  -- was the creation order, and "the operator's plans, newest first" is the
  -- read that follows section 4's sixth. A random key orders nothing.
  made_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Spec 2.9: an arm becomes at most one staged experiment and holds a
-- nullable reference to the one it became. Spec 5.1: the arm has no state
-- of its own - its status is that row's state, and a null reference records
-- that it has not been registered.
--
-- **The row is named for the thing and not for where it is drawn.** The
-- document calls it a column because the matrix of the sketch draws it as
-- one, and the same sketch draws the tuple's six members as rows - an axis
-- that cannot grow beside one that is generated and unbounded. Turn that
-- table and a schema naming the column would be describing a layout it does
-- not hold. `arm` is the word the Spec already uses for the thing itself.
--
-- **The reference is unique**, which is what holds the claim at most once:
-- two registrations racing on one column leave one staged experiment and
-- the loser finds the column already registered. Without it one column
-- would carry two frozen experiments and the matrix would read two arms
-- where the operator authored one.
CREATE TABLE plan_arm (
  -- **An arm is an identity and a name, and they are not the same member.**
  -- The name is the operator's word for the arm and the matrix's label, and
  -- section 2.9 has the operator trim and adjust a generated plan, so a
  -- rename is an ordinary act rather than an exceptional one. Were the name
  -- the key, a rename would cascade through every entry the arm holds and
  -- through anything else that had referred to it. It is one update here.
  arm_id         arm_id PRIMARY KEY DEFAULT weaver_key('ar'),
  plan_id        plan_id NOT NULL REFERENCES plan(plan_id) ON DELETE CASCADE,
  name           TEXT NOT NULL,

  experiment_id  BIGINT UNIQUE REFERENCES staged_experiment(experiment_id),

  -- Two arms of one plan do not share a label. The matrix draws the name,
  -- and two arms drawn alike are two the operator cannot tell apart.
  made_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT plan_arm_name_is_the_operator_s_own UNIQUE (plan_id, name)
);

-- **No index on `plan_id` alone.** The uniqueness above builds a btree whose
-- leading column is `plan_id`, which answers the only lookup these reads
-- make, and a second btree over the same leading column would be maintained
-- on every insert to answer nothing the first cannot.

-- Spec 2.9: an entry names a member of the tuple, carries its disposition,
-- and carries the value where it is held or the value set where it is
-- freed.
--
-- **The disposition is the entry's own and the status is the arm's.** An
-- entry that carried both could not say what a freed entry in a queued arm
-- is, which is both at once.
CREATE TABLE plan_entry (
  arm_id       arm_id NOT NULL REFERENCES plan_arm(arm_id) ON DELETE CASCADE,
  member       TEXT NOT NULL,

  disposition  TEXT NOT NULL,
  held_value   JSONB,
  freed_values JSONB,

  PRIMARY KEY (arm_id, member),

  CONSTRAINT plan_entry_disposition_is_held_or_freed
    CHECK (disposition IN ('held', 'freed')),

  -- The disposition and the value are one fact stated once: a held entry
  -- carries the value it holds, a freed entry carries the set it frees, and
  -- neither carries the other's member.
  -- **JSON null is not SQL NULL.** `held_value IS NOT NULL` admits the JSONB
  -- value `null`, which is a held entry carrying no value spelled the one
  -- way this check would not catch, so the absent-not-empty failure would
  -- reach the store through the gap between two meanings of the word.
  CONSTRAINT plan_entry_states_the_value_its_disposition_names
    CHECK (
      (disposition = 'held'
        AND held_value IS NOT NULL AND jsonb_typeof(held_value) <> 'null'
        AND freed_values IS NULL)
      OR
      (disposition = 'freed'
        AND freed_values IS NOT NULL AND held_value IS NULL)
    ),

  -- An array and not the empty one: section 5.4 has a sweep name one member
  -- **and its value set**, so a freed member over no values is a column that
  -- would register a sweep with no arms and produce no runs. 0001 holds the
  -- same shape for the artifact's digests.
  CONSTRAINT plan_entry_freed_values_is_an_array
    CHECK (freed_values IS NULL
           OR (jsonb_typeof(freed_values) = 'array' AND freed_values <> '[]'::jsonb))
);

-- Spec 2.9: an arm frees at most one member and holds the rest, section 5.4
-- having a sweep name one member and its value set. An arm that frees none
-- is the ordinary point experiment rather than a sweep, so the bound is one
-- and not exactly one.
CREATE UNIQUE INDEX plan_arm_frees_at_most_one_member
  ON plan_entry (arm_id) WHERE disposition = 'freed';

-- Spec 2.10: a named reference from a person to a run, and the one thing
-- this document takes from a commit graph. A run reachable from no root is
-- scaffolding; what must survive is what a bound cites, and a ref is how a
-- run says so.
--
-- Nothing in this document deletes a run. This row exists so that a later
-- act which does can tell what it is deleting.
CREATE TABLE ref (
  ref_id   ref_id PRIMARY KEY DEFAULT weaver_key('rf'),
  name     TEXT NOT NULL,
  -- The run it pins keeps the identity the record spelled, per section 2.2.
  -- A ref is authored here and the run it names was not, so the two keys of
  -- this one row are the convention's two halves side by side.
  run_id   TEXT NOT NULL REFERENCES run(run_id),
  author   TEXT,
  version  BIGINT NOT NULL DEFAULT 1,
  made_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Spec 2.7. The roots of section 2.10's reachability are three - a ref, a
-- plan's parent run, and the parent run of a staged experiment that has not
-- returned - and each needs an index or a sweep finds it by a walk.
--
-- **The third is not 0007's lineage index.** That one is on `run
-- (parent_run_id)`, which answers a branch's siblings, and the third root
-- lives on `staged_experiment (parent_run_id)`, which had no index at all:
-- a foreign key constrains and does not index, which is the identical
-- finding the review of PR #540 made against 0007 and which the first form
-- of this migration repeated while claiming it was fixed.
CREATE INDEX ref_by_run ON ref (run_id);
CREATE INDEX plan_by_parent ON plan (parent_run_id);
CREATE INDEX staged_experiment_by_parent ON staged_experiment (parent_run_id);
