-- Spec 2.12: the register of agents, and the listener's own row.
--
-- **The register of agents is one table, and section 1's "registry" is the
-- whole store.** The two readings are told apart in the Spec and here: this
-- file builds the register, which is the one table that holds agents.
--
-- **An authored row with observed members, written by two writers at
-- disjoint members** (Spec section 3). The register verb authors the name,
-- the box, the author and the credentials under section 3.2's version. The
-- link writes what it observed: each plane's link state and address, and the
-- tuple and the load state as admin reported them, each ordered on the
-- listener's arrival sequence and never on the row's version.

-- Spec 2: an authored row's identity says what it addresses. `ag-` and
-- sixteen hex, generated by the store through the function migration 0009
-- declared once for every kind.
CREATE DOMAIN agent_id AS TEXT CHECK (VALUE ~ '^ag-[0-9a-f]{16}$');

CREATE TABLE agent (
  agent_id      agent_id PRIMARY KEY DEFAULT weaver_key('ag'),

  -- **The name is immutable** (Spec 2.12): admin knows the agent by it on
  -- its box and both connectors' configs carry it, so a renamed row would
  -- refuse its own connectors at the hello. The trigger below holds it; a
  -- different name is a different registration.
  name          TEXT NOT NULL,
  -- The box it reports from, as registered: a claim the operator made,
  -- kept apart from the address the listener observed below.
  box           TEXT NOT NULL,

  -- Section 3.2's members. The author has no default: a null is passed
  -- rather than fallen into. The version is the store's counter and a
  -- register verb's edit refuses against a stale one.
  author        TEXT,
  version       BIGINT NOT NULL DEFAULT 1,
  registered_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- **The two credentials, each a fingerprint and never a key** (Spec 2.12,
  -- 8). The fingerprint is SHA-256 over the client certificate's DER, and
  -- the checks below are what make the column unable to hold a key: a PEM
  -- or a DER is not sixty-four hex digits. This is the schema instrument of
  -- web-client-credential-stored-as-fingerprint-never-key, the posture of
  -- section 2.8's bearer digest applied to a certificate.
  gate_fingerprint   TEXT NOT NULL,
  gate_state         TEXT NOT NULL DEFAULT 'live',
  gate_state_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  admin_fingerprint  TEXT NOT NULL,
  admin_state        TEXT NOT NULL DEFAULT 'live',
  admin_state_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- **Each credential records the authority that signed it**, as that
  -- authority certificate's fingerprint, so a rotation of the authority
  -- can revoke whatever was signed by another: the reconciliation that
  -- makes a lost lock session harmless rather than merely unlikely.
  gate_authority     TEXT NOT NULL,
  admin_authority    TEXT NOT NULL,

  -- **Each plane's link state is the listener's word about its own
  -- connections** (Spec 2.12, 8): connected or not, the date it last
  -- changed, the incarnation of the connection that wrote it (so a stale
  -- teardown cannot mark a plane missing after its replacement was
  -- admitted), and the address the listener observed with its date. Reset
  -- at every listener start, which is why a flag here is never read as
  -- presence by any process but the one that set it.
  gate_connected     BOOLEAN NOT NULL DEFAULT false,
  gate_link_at       TIMESTAMPTZ,
  gate_incarnation   BIGINT,
  gate_address       TEXT,
  gate_address_at    TIMESTAMPTZ,
  admin_connected    BOOLEAN NOT NULL DEFAULT false,
  admin_link_at      TIMESTAMPTZ,
  admin_incarnation  BIGINT,
  admin_address      TEXT,
  admin_address_at   TIMESTAMPTZ,

  -- **The tuple and the load state as admin reported them**, each with
  -- admin's date and the arrival sequence (epoch, arrival) that landed it,
  -- per Spec 2.12: a member takes the observation with the higher sequence,
  -- the date decides nothing, and a replayed event writes neither.
  tuple              JSONB,
  tuple_at           TIMESTAMPTZ,
  tuple_epoch        BIGINT,
  tuple_arrival      BIGINT,
  load_state         TEXT,
  load_state_at      TIMESTAMPTZ,
  load_epoch         BIGINT,
  load_arrival       BIGINT,

  CONSTRAINT agent_name_is_well_formed
    CHECK (name ~ '^[A-Za-z0-9_-]+$'),
  -- `.` and `..` are excluded by name: a box names a directory under the
  -- operator's output path, and those two would name its parent.
  CONSTRAINT agent_box_is_well_formed
    CHECK (box ~ '^[A-Za-z0-9_.-]+$' AND box NOT IN ('.', '..')),
  CONSTRAINT agent_gate_fingerprint_is_sha256_hex
    CHECK (gate_fingerprint ~ '^[0-9a-f]{64}$'),
  CONSTRAINT agent_admin_fingerprint_is_sha256_hex
    CHECK (admin_fingerprint ~ '^[0-9a-f]{64}$'),
  CONSTRAINT agent_fingerprints_differ
    CHECK (gate_fingerprint <> admin_fingerprint),
  CONSTRAINT agent_gate_authority_is_sha256_hex
    CHECK (gate_authority ~ '^[0-9a-f]{64}$'),
  CONSTRAINT agent_admin_authority_is_sha256_hex
    CHECK (admin_authority ~ '^[0-9a-f]{64}$'),
  CONSTRAINT agent_gate_state_is_one_of
    CHECK (gate_state IN ('live', 'revoked')),
  CONSTRAINT agent_admin_state_is_one_of
    CHECK (admin_state IN ('live', 'revoked')),
  CONSTRAINT agent_tuple_sequence_is_whole
    CHECK ((tuple_epoch IS NULL) = (tuple_arrival IS NULL)),
  CONSTRAINT agent_load_sequence_is_whole
    CHECK ((load_epoch IS NULL) = (load_arrival IS NULL))
);

-- The hello's lookup is by fingerprint (Spec 8), before any byte of the
-- roster is read, so each plane's column is the index that lookup hits.
CREATE UNIQUE INDEX agent_gate_fingerprint ON agent (gate_fingerprint);
CREATE UNIQUE INDEX agent_admin_fingerprint ON agent (admin_fingerprint);

-- **At most one row per box and name holds live credentials** (Spec 2.12),
-- the schema instrument of web-one-live-row-per-box-and-name. Re-registering
-- a live pair retires the previous row by revoking its credentials in the
-- same transaction, which this index forces: an insert that did not would
-- refuse here rather than open a second row for one physical agent.
CREATE UNIQUE INDEX agent_one_live_row_per_box_and_name ON agent (box, name)
  WHERE gate_state = 'live' OR admin_state = 'live';

CREATE FUNCTION agent_name_is_immutable() RETURNS trigger AS $$
BEGIN
  IF NEW.name IS DISTINCT FROM OLD.name THEN
    RAISE EXCEPTION 'the registered agent''s name is immutable (weaver-web-Spec section 2.12); a rename is a new registration';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER agent_name_is_immutable
  BEFORE UPDATE OF name ON agent
  FOR EACH ROW EXECUTE FUNCTION agent_name_is_immutable();

-- **The listener's own row, one and only one** (Spec 2.12, 8): the epoch,
-- incremented once at every listener start in the same transaction as the
-- startup reset, so every observation a process lands orders above every
-- one the last process left. The check and the constant key hold it to one
-- row.
CREATE TABLE listener (
  one        BOOLEAN PRIMARY KEY DEFAULT true,
  epoch      BIGINT NOT NULL DEFAULT 0,
  started_at TIMESTAMPTZ,
  CONSTRAINT listener_is_one_row CHECK (one)
);

INSERT INTO listener DEFAULT VALUES;
